### ISSUE TITLE
Planet QGIS Plugin issues in new QGIS PR 3.16

### ISSUE THREAD

**Issue by mapninja** [planetlabs/qgis-planet-plugin#12] opened 2020-11-04 04:27 UTC
QGIS just released the new PR, and it's got the Planet Plugin a little breakey. I installed in a clean User profile, and was able to search, add basemaps, search dailies, etc... but ordering failed in the monitoring window. THen, when saving a QGIS doc, Planet starts throwing python errors, some of which are pasted here. Note that these errors are persistent after uninstalling the plugin, too. 

  System Version:	macOS 10.15.7 (19H2)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

QGIS version | 3.16.0-Hannover | QGIS code revision | 4af1cbfb97
-- | -- | -- | --
Compiled against Qt | 5.14.2 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.1.2 | Running against GDAL/OGR | 3.1.2
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | macOS 10.15
Active python plugins | quick_map_services; processing_saga_nextgen; processing_wbt; processing; db_manager; MetaSearch

```
2020-11-03T19:46:00     WARNING    Traceback (most recent call last):
              File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/pe_plugin.py", line 428, in project_saved
              File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/planet_api/p_client.py", line 109, in getInstance
              File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/planet_api/p_client.py", line 157, in set_proxy_values
             TypeError: 'NoneType' object is not iterable
             
2020-11-03T20:19:50     WARNING    Traceback (most recent call last):
              File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/pe_plugin.py", line 428, in project_saved
              File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/planet_api/p_client.py", line 109, in getInstance
              File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/planet_api/p_client.py", line 157, in set_proxy_values
             TypeError: 'NoneType' object is not iterable
```

When reinstalling Planet, these pop up:

```
Couldn't load plugin 'planet_explorer' due to an error when calling its initGui() method 

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 359, in startPlugin
    plugins[packageName].initGui()
  File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/pe_plugin.py", line 320, in initGui
    PlanetClient.getInstance().loginChanged.connect(replace_apikeys)
  File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/planet_api/p_client.py", line 109, in getInstance
    PlanetClient.__instance.set_proxy_values()
  File "/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/planet_api/p_client.py", line 157, in set_proxy_values
    excluded = any([base_url.startswith(url.lower()) for url in noProxyUrls])
TypeError: 'NoneType' object is not iterable


Python version: 3.7.7 (default, Sep 22 2020, 10:25:18) [Clang 12.0.0 (clang-1200.0.32.2)] 
QGIS version: 3.16.0-Hannover Hannover, 4af1cbfb97 

Python Path:
/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/planet_explorer/extlibs
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/numba-0.50.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/opencv_contrib_python-4.3.0.36-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/geopandas-0.8.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/snuggs-1.4.7-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/netCDF4-1.5.3-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/numpy-1.19.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/rasterio-1.1.5-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pandas-1.1.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Rtree-0.9.4-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Fiona-1.8.13.post1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/scipy-1.5.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/affine-2.3.0-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/Pillow-7.2.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/matplotlib-3.3.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/pyproj-2.6.0-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python37.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/GDAL-3.1.2-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/cftime-1.2.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/patsy-0.5.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/click_plugins-1.1.1-py3.7.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages/statsmodels-0.11.1-py3.7-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.7/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.7
/Users/maples/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/maples/Dropbox/Fundamentals/L11
```

**Comment by stewartmacdonald** [comment] 2020-11-13 03:54
I get the same errors with QGIS version `3.10.6-A Coruña`.

**Comment by volaya** [comment] 2020-11-17 07:00
This error should be fixed already. You can either install the most recent version, or just enter a dummy value in the "no proxy urls" box in the QGIS settings. The issue is caused by a wrong handling of an empty value for that parameter

**Closed** 2021-09-13 16:55 UTC
